site_name: P2Pool-API
site_url: https://hreikin.github.io/p2pool-api
repo_name: hreikin/p2pool-api
repo_url: https://github.com/hreikin/p2pool-api
copyright: MIT License
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: deep orange
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
nav:
  - "Home": "README.md"
  - "Usage": "usage.md"
  - "Examples": "examples.md"
  - "Logging": "logger.md"
  - "Properties": "properties.md"
  - "Reference":
    - "Classes":
      - "P2PoolAPI": "reference/classes/api.md"
      - "P2PoolDatabase": "reference/classes/db.md"
    - "Exceptions":
      - "P2PoolAPIError": "reference/exceptions/p2poolapierror.md"
      - "P2PoolConnectionError": "reference/exceptions/p2poolconnectionerror.md"
      - "P2PoolDatabaseError": "reference/exceptions/p2pooldatabaseerror.md"
    - "Models":
      - "Console": "reference/models/console.md"
      - "P2P": "reference/models/p2p.md"
      - "Stratum": "reference/models/stratum.md"
      - "NetworkStats": "reference/models/networkstats.md"
      - "PoolBlocks": "reference/models/poolblocks.md"
      - "PoolStats": "reference/models/poolstats.md"
      - "StatsMod": "reference/models/statsmod.md"
  - "Contributing": "CONTRIBUTING.md"

plugins:
  - search
  - mkdocstrings